[package]
name = "yee_player"
version = "0.1.0"
authors = ["OTOMariK"]
edition = "2018"

[dependencies]
lazy_static = "*"
log = "*"
env_logger = "*"

winit = "0.22"
raw-window-handle = "*"
wgpu = "*"

legion = "*"

rodio = "*"

ron = "*"
serde= "*"
zerocopy= "*"

futures="*"