[package]
name = "yee_player"
version = "0.1.0"
authors = ["OTOMariK"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.7"

winit = "0.22"
raw-window-handle = "0.3"
wgpu = "0.6"

legion = "0.3"

rodio = "0.11"

serde= "*"
ron = "0.6"
zerocopy= "0.3"

futures="0.3"